In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pic = np.load('digits/digits_images.npy')
label = np.load('digits/digits_lable.npy')

In [3]:
pic

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [6]:
label

array([0, 1, 2, ..., 8, 9, 8])

In [4]:
len(pic)

1797

In [5]:
len(label)

1797

In [8]:
pic.shape

(1797, 64)

In [9]:
label.shape

(1797,)

### 使用留出法拆分训练集和测试集，留出10%作为测试集

In [7]:
from ML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(pic, label, test_size=0.1, seed=10)

In [10]:
len(X_train)

1618

In [11]:
len(X_test)

179

In [12]:
len(y_train)

1618

In [13]:
len(y_test)

179

### 训练KNN模型

In [14]:
from ML.knn import KNeighborClassifier

In [17]:
knn_clf = KNeighborClassifier()
knn_clf.fit(X_train, y_train)

预测测试数据集中的前10个

In [22]:
knn_clf.predict(X_test[:10])

array([5, 2, 5, 4, 8, 2, 4, 3, 3, 0])

In [23]:
y_test[:10]

array([5, 2, 5, 4, 8, 2, 4, 3, 3, 0])

In [21]:
%%time
knn_clf.score(X_test, y_test)

CPU times: user 1.7 s, sys: 0 ns, total: 1.7 s
Wall time: 1.7 s


0.9832402234636871

### 搜索最佳的超参数k和n的取值

In [25]:
%%time
best_score = 0
best_k = 0

# k从1到10循环测试，找出最优k值
for k in range(1, 11):
    knn_clf = KNeighborClassifier(k=k)
    knn_clf.fit(X_train, y_train)
    
    score = knn_clf.score(X_test, y_test)
    
    if(score > best_score):
        best_score = score
        best_k = k
        
print('best_k =', best_k)
print('best_score =', best_score)

best_k = 3
best_score = 0.9888268156424581
CPU times: user 17.6 s, sys: 0 ns, total: 17.6 s
Wall time: 17.6 s


In [26]:
%%time
best_score = 0
best_k = 0
best_p = 0

# k从1到10循环测试，找出最优k值
for k in range(1, 11):
    # p从1到10循环测试，找出最优p值
    for p in range(1, 11):
        knn_clf = KNeighborClassifier(k=k, p=p)
        knn_clf.fit(X_train, y_train)
        score = knn_clf.score(X_test, y_test)
        
        if(score > best_score):
            best_score = score
            best_k = k
            best_p = p
        
print('best_k =', best_k)
print('best_p =', best_p)
print('best_score =', best_score)

best_k = 1
best_p = 3
best_score = 0.9888268156424581
CPU times: user 4min 9s, sys: 6.16 ms, total: 4min 9s
Wall time: 4min 9s
